### ISSUE TITLE
possible memory leaks when not initialized properly

### ISSUE THREAD

**Issue by pvyhnal-generalbytes** [dashevo/dashj#28]
When dashj is initialized with just `Context.get().initDash(false, true);` it leaks memory as `MasternodeManager#mapSeenMasternodePing` is populated but never cleaned.

`Context.get().setLiteMode(false);` has to be called to start ThreadCheckDarkSendPool which cleans the map.

Also `mapTxLockVotes` seems to be getting filled with entries that will never be removed because `TransactionLockVote#isExpired` is never true on them

This seems to be a problem only when lite mode = false. I tried using the lite mode but it had some problems discovering peers. What exactly is is the non-lite mode used for?

Thanks

**Comment by pvyhnal-generalbytes** [comment]
it seems that even if ThreadCheckDarkSendPool is started the way I described above it stops after some time and the memory leak is back. It's probably better to use the lite mode.

**Comment by HashEngineering** [comment]
LiteMode is to run a node without trying to get the list of masternodes, governance objects and governance votes. When LiteMode is OFF then the node tries to get a list of all of these other Dash objects.  OFF is experimental and will soon become partially obsolete with the activation of Spork 15.   

The Dash Wallet android app uses LiteMode and does not have issues finding peers.  There is a fix for finding peers that will be added.  I will comment later with the commit of that fix.

**Comment by HashEngineering** [comment]
Based on your first comment, it would seem that you want litemode ON as it seems to solve most of the problems.  Additionally, in our next release of dashj 0.15.1, we will disable acquisition of masternode objects.  This will resolve the memory leak of this:  `MasternodeManager#mapSeenMasternodePing`, but won't address other issues.  The other issues will need to be looked at further to determine why `mapTxLockVotes` is never emptied while litemode is OFF. 

https://github.com/dashevo/dashj/pull/30/commits/6ffd45ccb02ae3e08151a3aabf721e0eef344510 will address connectivity issues.  Older nodes such as 0.12.3.x will not connect to dashj.

https://github.com/dashevo/dashj/pull/30/commits/7eda2cea72b48ba25177bb9e6338eb3e18f0c257 will ensure that dashj follows the correct chain (the same as the 0.13.x nodes).

**Comment by HashEngineering** [comment]
We are investigating the memory leaks with `mapTxLockVotes` and found that in full verification mode, the `confirmedHeight` is not initialized, therefore `TransactionLockVote.isExpired` never returns true.  This applies to several other `InstantSend` objects.

**Comment by pvyhnal-generalbytes** [comment]
FYI over the weekend downloading of new transactions was stuck at #1033575 for me (don't know the reason yet) but it triggered another memory leak in `org.bitcoinj.core.AbstractBlockChain#orphanBlocks`. Its already reported in https://github.com/bitcoinj/bitcoinj/issues/997

**Comment by HashEngineering** [comment]
https://github.com/dashevo/dashj/pull/30/commits/30e3911ac37d6e13632e7999b922a72bc7034605 will resolve the InstantSend related memory leaks.

My full node didn't get stuck on a particular block that I know of over the weekend.  Regarding orphans, only with BloomFilters do they get removed.  Of course in a full node, they stay in memory.  I am not sure if we will get much help from the bitcoinj people, especially for full verification mode.

**Comment by pvyhnal-generalbytes** [comment]
PR in bitcoinj: https://github.com/bitcoinj/bitcoinj/pull/1738

**Comment by HashEngineering** [comment]
The above PR for bitcoinj looks simple, I will test it out on dashj.

**Comment by HashEngineering** [comment]
Testing complete.   Memory leaks fixed.

**Comment by schildbach** [comment]
So you're saying the above PR fixes your observed memory leak?
