### ISSUE TITLE
Memory leak in Peer

### ISSUE THREAD

**Issue by pvyhnal-generalbytes** [dashevo/dashj#31]
There is a possible memory leak in Peer class (originally form bitcoinj) when a peer does not respond to Ping or when a peer does not send announced transactions. See PR: https://github.com/bitcoinj/bitcoinj/pull/1726 or maybe wait for a review in bitcoinj before using it

**Comment by HashEngineering** [comment]
I will wait for the review while I do some of my own investigation.

**Comment by HashEngineering** [comment]
Two commits from bitcoinj have been added to this PR #35.  We made a modification on the transaction limit to include InstantSend transactions.
