### ISSUE TITLE
Add git submodule steps in building instructions

### ISSUE THREAD

**Issue by sambarboza** [dashevo/dashj#33]
Project won't build before running `git submodule init` & `git submodule update`

**Comment by HashEngineering** [comment]
I have just built this repo from a fresh `clone` using `git submodule init` && `git submodule update`

What are the errors that you get?

**Comment by HashEngineering** [comment]
@sambarboza I misread your first comment.

Yes, we need to update the build documentation.

without the submodule commands, one can build with these flags:  `-Pno-build-bls -DskipTests`

**Comment by HashEngineering** [comment]
These instructions are now part of 0.15.1
