### ISSUE TITLE
Stuck at block 1037027

### ISSUE THREAD

**Issue by HashEngineering** [dashevo/dashj#34]
In our testing of full block verification mode, we found that BIP30 fails with this block:
https://explorer.dash.org/block/0000000000000005609b6426cc199fc3cec30dbdd19d1c483edcefa5c7e1b080 on this transaction:  https://explorer.dash.org/tx/c51691cd143bbb824f2b1046adff9db35373b67ff0100b9541a8bc5ab999790e

Block:  1037027

@pvyhnal-generalbytes - have you encountered something like this?

The transaction in question:  https://explorer.dash.org/tx/c51691cd143bbb824f2b1046adff9db35373b67ff0100b9541a8bc5ab999790e appeared in two blocks according to the block explorer with block times 3 seconds apart.  It could be that this has failed due to the same transaction being found in an orphan?

**Comment by pvyhnal-generalbytes** [comment]
No, this block and transaction was processed normally in my local test environment. We are on this fork/branch: https://github.com/GENERALBYTESCOM/dashj/tree/dash-0.13

**Comment by HashEngineering** [comment]
We found that the `hasUnspentOutputs` method of `LevelDBFullPrunedBlockStore` was incomplete and triggered an exception during a block reorganization.

**Comment by HashEngineering** [comment]
There was a bug in LevelDBFullPrunedBlockStore.  This will be addressed in a PR.

**Comment by HashEngineering** [comment]
This has been addressed here:
https://github.com/dashevo/dashj/pull/35/commits/08d8083890010efe426fca10f7e4e9920e202959

as part of #35 .
